# План:
1. Python
2. Numpy
3. Pandas
4. Regexp + regexp with dataframes
5. Texts
6. Matplotlib, Seaborn
7. Classification, clustering, binary, multiclass, multilabel
8. Metrics
9. Feature extraction
10. Pyspark/sql

<img src="gifs/start.gif" width="400">

# Python

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
    * Числа (7382, 3.14, 3+4j, Decimal, Fraction)
    * Строки ('net', "your's", u'радость')
    * Списки ([1, [2, 'three'], 4])
    * Словари ({'Alex': 2, 'Brian': 4})
    * Кортежи ('Leo', 21.7, 'single')
    * Множества (set(1,2,3), {'a', 'b', 'c'})
    * Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)

In [3]:
str1 = "ada".title()
str2 = "lovelace".title()
str3 = "was considered the world's first computer programmer."
str1+str2+ str3


"AdaLovelacewas considered the world's first computer programmer."

2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

In [11]:
str1 = "  \n123\n123\n"
print(str1.lstrip())
print('#####')
print(str1.rstrip())
print('#####')
print(str1.strip())
print('#####')

123
123

#####
  
123
123
#####
123
123
#####


3. Найти первое вхождение в строку подстроки (☆☆☆)

In [20]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"
s1.find(s2)
##your code

7

* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [22]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"
mas = s1.split('#')
mas
##your code

['Holy',
 'cow,',
 'Rick!',
 'I',
 'didn’t',
 'know',
 'hanging',
 'out',
 'with',
 'you',
 'was',
 'making',
 'me',
 'smarter!']

5. Полученный массив строк склеить через пробел (★☆☆)

In [24]:
' '.join(mas)

'Holy cow, Rick! I didn’t know hanging out with you was making me smarter!'

6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [31]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}

def fun(name, age, job):
    print(name + ' (age ' + str(age) + ') is a ' + job + '\n')

fun(personal_data[1][0], personal_data[1][1], personal_data[1][2])
fun(personal_data[2][0], personal_data[2][1], personal_data[2][2])
fun(personal_data[3][0], personal_data[3][1], personal_data[3][2])
##your code

Ann (age 29) is a Artist

Leo (age 54) is a Programmer

Tiffany (age 43) is a Shop Assistant



7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

In [34]:
def visokosn_year(year):
    if (year % 400 == 0):
        print('Yes')
    elif((year % 100 != 0) and (year % 4 == 0)):
        print('Yes')
    else:
        print('No')

visokosn_year(108)

Yes


8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [36]:
words = ['Not', 'my', 'cup', 'of', 'tea']
dic = {}
index = 0;
for i in words:
    dic[str(index)] = i
    index = index + 10
dic

##your code

{'0': 'Not', '10': 'my', '20': 'cup', '30': 'of', '40': 'tea'}

9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [40]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']
dogs.remove('border collie')
print(dogs)

dogs1 = ['border collie', 'australian cattle dog', 'labrador retriever']
del dogs1[1]
print(dogs1)
##your code

['australian cattle dog', 'labrador retriever']
['border collie', 'labrador retriever']


10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [44]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']
print([i.upper() for i in dogs[2:5]])
##your code

['AUSTRALIAN', 'CATTLE', 'DOG']


11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [47]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }
for i in pets.keys():
    print("name pets is {0}, it is {1}, owner is {2}, vaccinated is {3}".format(i, pets[i]['kind'], pets[i]['owner'], pets[i]['vaccinated']))
##your code

name pets is willie, it is dog, owner is eric, vaccinated is True
name pets is walter, it is cockroach, owner is eric, vaccinated is False
name pets is peso, it is dog, owner is chloe, vaccinated is True


12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [76]:
a1=set([2, 5, 6])
b1=set([2, 4, 8, 3, 5, 6, 0])
m = a.issubset(b)

##your code

13. Объединить несколько множеств (★☆☆)

In [77]:
a=set([10, 35, 6, 5])
b=set([2, 4, 8, 3, 5, 6, 35])
c=set([1, 4, 5, 35])
a = a.union(b)
a = a.union(c)
a
##your code

{1, 2, 3, 4, 5, 6, 8, 10, 35}

14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

In [78]:
print(a1.intersection(a))
print(b1.intersection(a))

{2, 5, 6}
{2, 3, 4, 5, 6, 8}


15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

(hint: .symmetric_difference())

In [81]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])
a.symmetric_difference(b)
##your code

{1, 2, 6, 7}

16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

In [86]:
f = open("data/credit_sample.txt")
print(f.read())
    

lastname,age,debt, occupation
Adrianov,25,30000,artist
Belkin,42,4000,programmer
Koltunov,32,100,sportsman
Loptev,25,30000, artist
Bobrov,42,4000,programmer
Karelin,32,100, sportsman


In [121]:
import json
f = open("data/credit_sample.txt")
a = set(['occupation'])
dic = {}
for line in f:
    line = line.strip()
    mas = line.split(',')
    print(mas)
    b = set([mas[3].strip()])
    print(b)
    dic[mas[0]] = mas[1:4]
    if (a.issubset(b) == False):
        a = a.union(b)
with open("data_file.json", "w") as write_file:
    json.dump(dic, write_file)
dic

['lastname', 'age', 'debt', ' occupation']
{'occupation'}
['Adrianov', '25', '30000', 'artist']
{'artist'}
['Belkin', '42', '4000', 'programmer']
{'programmer'}
['Koltunov', '32', '100', 'sportsman']
{'sportsman'}
['Loptev', '25', '30000', ' artist']
{'artist'}
['Bobrov', '42', '4000', 'programmer']
{'programmer'}
['Karelin', '32', '100', ' sportsman']
{'sportsman'}


{'Adrianov': ['25', '30000', 'artist'],
 'Belkin': ['42', '4000', 'programmer'],
 'Bobrov': ['42', '4000', 'programmer'],
 'Karelin': ['32', '100', ' sportsman'],
 'Koltunov': ['32', '100', 'sportsman'],
 'Loptev': ['25', '30000', ' artist'],
 'lastname': ['age', 'debt', ' occupation']}

### os, sys, datetime

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

In [3]:
import glob

In [8]:
[x.replace('gifs\\', '') for x in glob.glob('gifs/*.gif')]

['bender.gif',
 'cheers.gif',
 'inprogress.gif',
 'journey.gif',
 'pandas.gif',
 'remember.gif',
 'sleep.gif',
 'start.gif']

In [2]:
import os
gif = os.listdir("gifs")
mas = []
print(gif)
for i in gif:
    file, file_extension = os.path.splitext(i)
    if (file_extension != '.gif'):
        mas.append(i)
        print(file_extension)
#         gif.remove(i)
for i in mas:
    gif.remove(i)
print(gif)

['bender.gif', 'cheers.gif', 'end.jpg', 'inprogress.gif', 'journey.gif', 'linear.jpeg', 'ml_map.png', 'one-hot-encoding.png', 'one_hot.png', 'pandas.gif', 'pandas.jfif', 'remember.gif', 'sleep.gif', 'start.gif']
.jpg
.jpeg
.png
.png
.png
.jfif
['bender.gif', 'cheers.gif', 'inprogress.gif', 'journey.gif', 'pandas.gif', 'remember.gif', 'sleep.gif', 'start.gif']


18. Создать папку с названием temp и удалить её (★☆☆)

In [4]:
import os
os.mkdir("temp")
os.rmdir("temp")


19. Вывести переменные среды (★☆☆)

(hint: environ)

In [5]:
os.environ

environ{'ALLUSERSPROFILE': 'C:\\ProgramData',
        'APPDATA': 'C:\\Users\\18322440\\AppData\\Roaming',
        'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
        'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
        'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
        'COMPUTERNAME': 'CAB-WSN-0012389',
        'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
        'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
        'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
        'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
        'HOMEDRIVE': 'C:',
        'HOMEPATH': '\\Users\\18322440',
        'LOCALAPPDATA': 'C:\\Users\\18322440\\AppData\\Local',
        'LOGONSERVER': '\\\\LAKE5',
        'NUMBER_OF_PROCESSORS': '8',
        'OS': 'Windows_NT',
        'PATH': 'c:\\anaconda3\\Library\\bin;C:\\Users\\18322440\\AppData\\Roaming\\Python\\Python36\\site-packages\\pywin32_system32;c:\\anaconda3\\Library\\bin;C:\\Users\\18

20. Как игнорировать warrnings?

* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [10]:
from datetime import timedelta
from datetime import datetime
from datetime import date
from datetime import time

print(datetime.today())
print(datetime.today() - timedelta(1))
print(datetime.today() + timedelta(1))

2020-02-04 15:10:19.329560
2020-02-03 15:10:19.329560
2020-02-05 15:10:19.333560


22. Вывести день недели сегодняшней даты (★☆☆)

In [11]:
today = date.today()
today.weekday()

1

23. Получить список дат за предыдущую неделю (★★☆)

In [12]:
from datetime import timedelta
print(datetime.today)
for i in range(1, 8):
    print(datetime.today() - timedelta(i))

<built-in method today of type object at 0x0000000050549210>
2020-02-03 15:10:23.294600
2020-02-02 15:10:23.294600
2020-02-01 15:10:23.294600
2020-01-31 15:10:23.294600
2020-01-30 15:10:23.294600
2020-01-29 15:10:23.294600
2020-01-28 15:10:23.294600


24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [13]:
from datetime import datetime
datetime.now().strftime("%Y.%m.%d %H:%M:%S")

'2020.02.04 15:10:24'

25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [14]:
from datetime import timedelta
print(datetime.now())
print(datetime.now() - timedelta(7))

2020-02-04 15:10:25.439144
2020-01-28 15:10:25.439144


# Numpy

### numpy в картинках (реально лучший):

https://jalammar.github.io/visual-numpy/

In [1]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [2]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [3]:
mas = [1,2,3,4]
np.size(mas)

4

3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [4]:
mas = np.zeros(11)
mas[4] = 1
mas

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.])

4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [5]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [6]:
vec = np.arange(10, 51)
vec = vec[::-1]
vec

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Найти индексы не нулевых эемелентов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [8]:
np.array([1,2,0,0,4,0]).nonzero()

(array([0, 1, 4], dtype=int64),)

8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [9]:
mas = np.random.random((10, 10))
print(mas.max())
print(mas.min())
print(mas.mean())

0.989780279365
0.0043607218833
0.540778580175


9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

In [18]:
mas = np.zeros((8, 8))
mas[1::2, ::2] = 1
mas[::2, 1::2] = 1
mas

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])

10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

In [24]:
mas = np.random.random((5,5))
print(mas)
mn = mas.mean()
st = mas.std()
for i in range(len(mas)):
    for x in range(len(mas[i])):
        mas[i][x] = (mas[i][x] - mn)/st
print(mas)

[[ 0.92649421  0.56911532  0.40306357  0.55143412  0.97680183]
 [ 0.06234855  0.67243488  0.16539409  0.35813699  0.00536283]
 [ 0.42103996  0.00677937  0.7321447   0.20485345  0.92312065]
 [ 0.11409804  0.36467558  0.22247594  0.96354057  0.96224701]
 [ 0.76798239  0.95724423  0.68736134  0.80431292  0.66284231]]
[[ 1.18607583  0.09101472 -0.41779211  0.03683694  1.34022571]
 [-1.46179268  0.40760094 -1.14604609 -0.5554537  -1.63640524]
 [-0.36270982 -1.63206475  0.59056053 -1.02513685  1.17573873]
 [-1.30322467 -0.5354185  -0.97113896  1.29959127  1.29562764]
 [ 0.70037246  1.28029838  0.45333779  0.8116945   0.37820791]]


11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

In [29]:
mas1 = np.array([1,2,3,4,5,6,7,8,9,0])
mas2 = np.array([1,-2,-3,-4, 5,-6,-7,-8,-9,0])
np.intersect1d(mas1, mas2)

array([0, 1, 5])

12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

In [43]:
mas = np.random.random((5,5))
for i in range(len(mas)):
    for x in range(len(mas[i])):
        mas[i][x] = int(mas[i][x])
print(mas)

mas = np.random.random((5,5))
print(mas * 0)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

In [48]:
mas = np.random.random(10)
mas.sort()
mas

array([ 0.08382731,  0.2075753 ,  0.22042075,  0.2407173 ,  0.37263136,
        0.50949032,  0.74602068,  0.76343666,  0.81916268,  0.84277485])

14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

In [50]:
mas1 = np.random.random(10)
mas2 = np.random.random(10)
print(np.allclose(mas1, mas2))
print(np.array_equal(mas1, mas2))

False
False


15. Создать рандомный ветор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

In [55]:
mas = np.random.random(10)
mas[np.argmax(mas)] = -1
print(mas)

[ 0.42120627  0.51245526  0.30510026  0.32249814  0.74946432  0.68189416
  0.67569159 -1.          0.53751224  0.43471553]


16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [81]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(Z)
print(v)
print(np.abs(Z - v))
index = np.argmin(np.abs(Z - v))
print(Z[index])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
54.58222904634449
[ 54.58222905  53.58222905  52.58222905  51.58222905  50.58222905
  49.58222905  48.58222905  47.58222905  46.58222905  45.58222905
  44.58222905  43.58222905  42.58222905  41.58222905  40.58222905
  39.58222905  38.58222905  37.58222905  36.58222905  35.58222905
  34.58222905  33.58222905  32.58222905  31.58222905  30.58222905
  29.58222905  28.58222905  27.58222905  26.58222905  25.58222905
  24.58222905  23.58222905  22.58222905  21.58222905  20.58222905
  19.58222905  18.58222905  17.58222905  16.58222905  15.58222905
  14.58222905  13.58222905  12.58222905  11.58222905  10.58222905
   9.58222905   8.58222905   7.58222905   6.58222905   5.58222905
   4.58222905   3

17. Посчитать среднее для каждой строки матрицы (★★☆)

In [60]:
Z = np.random.random((10,10))
print(Z)
for i in Z:
    print(i.mean())

[[ 0.66198095  0.91986068  0.45863159  0.64999406  0.79431408  0.30780948
   0.42379152  0.27294419  0.0270965   0.38555886]
 [ 0.19914885  0.22782019  0.75355101  0.09048871  0.78796234  0.6126083
   0.91230565  0.3576637   0.0416151   0.96144375]
 [ 0.48843799  0.82954119  0.42704807  0.86470193  0.90199737  0.3512769
   0.76172569  0.06997526  0.63126017  0.19913166]
 [ 0.30522398  0.52145134  0.51806406  0.40122864  0.58986414  0.53006742
   0.27578085  0.78208747  0.94147176  0.43679646]
 [ 0.11043865  0.53310815  0.70558555  0.62867313  0.52998749  0.77507302
   0.17247949  0.11949631  0.66640022  0.86891498]
 [ 0.00358924  0.6155814   0.62152348  0.57056873  0.32920183  0.97393111
   0.52129708  0.15712116  0.36004987  0.21814596]
 [ 0.11521952  0.54606666  0.21908582  0.83335947  0.6608179   0.26286681
   0.93356905  0.40462647  0.24831754  0.14890469]
 [ 0.72305269  0.67335633  0.30108121  0.91009084  0.01641037  0.86546784
   0.35286887  0.45020238  0.10600541  0.27743968]
 [

18. Посчитать среднее со скользящим окном над массивом (★★★)

(hint: np.cumsum)

In [67]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
mas = np.arange(20)
moving_average(mas)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.])

<img src="gifs/bender.gif" width="400">

# Regular expressions

* Cупер статья на все времена. Особенно понятно все про такие сложные штуки как lookaround. 

https://habr.com/ru/post/349860/


* Задания на регулярки

https://regexone.com/

* На этом сайте удобно тестировать регулярку, которую мучаешь, можно написать несколько примеров и тестировать на них. Важно не забывать выбирать Python:

https://regex101.com/

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

In [96]:
import re
with open("data/rejson.txt") as f:
    s = f.read()
    
print(s)
re.findall(r"'\w*': '\w*'", s)


"{'233880bb4c50d247f84edc9cac9e6e29_2308194320': {'event_ids': [77], 'inn': '2308194320', 'master_guid': '233880bb4c50d247f84edc9cac9e6e29_2308194320', 'weight': 0}, '233880bb4c50d247f84edc9cac9e6e29_3015058150': {'event_ids': [77], 'inn': '3015058150', 'master_guid': '233880bb4c50d247f84edc9cac9e6e29_3015058150', 'weight': 1}, '233880bb4c50d247f84edc9cac9e6e29_6722014606': {'event_ids': [77], 'inn': '6722014606', 'master_guid': '233880bb4c50d247f84edc9cac9e6e29_6722014606', 'weight': 0}, '233880bb4c50d247f84edc9cac9e6e29_7104019979': {'event_ids': [77], 'inn': '7104019979', 'master_guid': '233880bb4c50d247f84edc9cac9e6e29_7104019979', 'weight': 0}, '233880bb4c50d247f84edc9cac9e6e29_7703425673': {'event_ids': [77], 'inn': '7703425673', 'master_guid': '233880bb4c50d247f84edc9cac9e6e29_7703425673', 'weight': 0}, '233880bb4c50d247f84edc9cac9e6e29_7708740277': {'event_ids': [77], 'inn': '7708740277', 'master_guid': 'ef2523f479fb766cacb89c58ec1e668f_7708740277', 'weight': 0}, '233880bb4c50d

["'inn': '2308194320'",
 "'master_guid': '233880bb4c50d247f84edc9cac9e6e29_2308194320'",
 "'inn': '3015058150'",
 "'master_guid': '233880bb4c50d247f84edc9cac9e6e29_3015058150'",
 "'inn': '6722014606'",
 "'master_guid': '233880bb4c50d247f84edc9cac9e6e29_6722014606'",
 "'inn': '7104019979'",
 "'master_guid': '233880bb4c50d247f84edc9cac9e6e29_7104019979'",
 "'inn': '7703425673'",
 "'master_guid': '233880bb4c50d247f84edc9cac9e6e29_7703425673'",
 "'inn': '7708740277'",
 "'master_guid': 'ef2523f479fb766cacb89c58ec1e668f_7708740277'",
 "'inn': '7728355650'",
 "'master_guid': 'b8c8c46467e81d5d43bd2a5cc5db85cd_7728355650'",
 "'inn': '7806495859'",
 "'master_guid': '7b0bdb98f0a36507d283bc7989389524_7806495859'",
 "'inn': '7816158919'",
 "'master_guid': '233880bb4c50d247f84edc9cac9e6e29_7816158919'"]

# Pandas

* Pandas в картинках

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* 🐼реально классный твиттер чувака с крутыми pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849

<img src="gifs/inprogress.gif" width="400">