# План:
1. Python
2. Numpy
3. Pandas
4. Regexp + regexp with dataframes
5. Texts
6. Matplotlib, Seaborn
7. Classification, clustering, binary, multiclass, multilabel
8. Metrics
9. Feature extraction
10. Pyspark/sql

<img src="gifs/start.gif" width="400">

# Python

* Целая куча упражнений на типы данных\операторы и функции

https://www.w3resource.com/python-exercises/

Типы данных:
    * Числа (7382, 3.14, 3+4j, Decimal, Fraction)
    * Строки ('net', "your's", u'радость')
    * Списки ([1, [2, 'three'], 4])
    * Словари ({'Alex': 2, 'Brian': 4})
    * Кортежи ('Leo', 21.7, 'single')
    * Множества (set(1,2,3), {'a', 'b', 'c'})
    * Файлы (open('myfile', 'r'))

1. Склеить 3 подстроки "ada", "lovelace", "was considered the world's first computer programmer.". Первые две строки сделать с большой буквы.  (★☆☆)

2. Удаление лишних пробельных символов справа, слева, с обоих сторон  (☆☆☆)

3. Найти первое вхождение в строку подстроки (☆☆☆)

In [40]:
s1="But if you stick with me, I’m gonna accomplish great things, Morty, and you’re gonna be part of ’em."
s2="you"

##your code

* isdigit - состоит ли строка из цифр;
* isalpha - состоит ли строка из букв;
* isalnum - состоит ли строка из цифр или букв;
* islower - состоит ли строка из символов в нижнем регистре;
* isupper - состоит ли строка из символов в верхнем регистре;
* istitle - начинаются ли слова в строке с заглавной буквы.

4. Разбить строку по разделителю (☆☆☆)

In [ ]:
s1="Holy#cow,#Rick!#I#didn’t#know#hanging#out#with#you#was#making#me#smarter!"

##your code

5. Полученный массив строк склеить через пробел (★☆☆)

6. Вывести данные из словаря в три строки в виде "NAME (age AGE) is a JOB" (★☆☆)

(hint: .format())

In [ ]:
personal_data = {1: ("Ann", 29, "Artist"), 
               2: ("Leo", 54, "Programmer"), 
               3: ("Tiffany", 43, "Shop Assistant")}

##your code

7. Требуется определить, является ли данный год високосным. (год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.)  (★★☆)

Входные данные: Вводится единственное число - номер года (целое, положительное, не превышает 30000).

Выходные данные: Требуется вывести слово YES, если год является високосным и NO - в противном случае.

8. Закодируйте каждый элемент списка слов числом, результат сопоставления (слово-число) поместите в словарь.  (★☆☆)

In [44]:
words = ['Not', 'my', 'cup', 'of', 'tea']

##your code

9. Удалить второй элемент из списка по индексу\по значению  (★☆☆)

In [ ]:
dogs = ['border collie', 'australian cattle dog', 'labrador retriever']

##your code

10. Вывести срез списка с 3 по 5 элемент включительно и все слова перевести в верхний регистр (★☆☆)

In [45]:
dogs = ['border', 'collie', 'australian', 'cattle', 'dog', 'labrador', 'retriever']

##your code

11. Словарь словарей. Вывести из словаря для каждого питомца его имя, породу, имя владельца, и наличие прививки. Строку вывода формировать через .format() (★☆☆)

In [ ]:
pets = {'willie': {'kind': 'dog', 'owner': 'eric', 'vaccinated': True},
        'walter': {'kind': 'cockroach', 'owner': 'eric', 'vaccinated': False},
        'peso': {'kind': 'dog', 'owner': 'chloe', 'vaccinated': True},
        }

##your code

12. Проверить является ли множество подмножеством другого множества  (★☆☆)

In [49]:
a=set([2, 5, 6])
b=set([2, 4, 8, 3, 5, 6])

##your code

13. Объединить несколько множеств (★☆☆)

In [ ]:
a=set([10, 35, 6, 5])
b=set([2, 4, 8, 3, 5, 6, 35])
с=set([4, 5, 35])

##your code

14. Посчитать пересечение множества b с остальными из предыдущего задания  (★★☆)

(hint: set.intersection(other, ...) (или set & other &) )

15. Вывести множество из элементов, встречающихся в одном множестве, но не встречающиеся в обоих. (★★☆)

(hint: .symmetric_difference())

In [51]:
a=set([1, 2, 3, 4, 5])
b=set([3, 4, 5, 6, 7])

##your code

16. Предположим, есть файл с данными клиентов. В качестве простого примера воьзьмем txt-файл следующего содержания:

    lastname,age,debt,occupation
    
    Adrianov,25,30000,artist
    
    Нужно считать файл data/credit_sample.txt.
    Сделать словарь вида:
        {lastname: (age,debt,occupation)}
    
    Посчитать сколько уникальных профессий получилось в словаре.
    
    Результат записать в json (★★★)

### os, sys, datetime

17. Получить список файлов в папке gifs/ и оставить только файлы с расширением .gif (★★☆)

18. Создать папку с названием temp и удалить её (★☆☆)

In [3]:
import os
os.mkdir("temp")
os.rmdir("temp")

19. Вывести переменные среды (★☆☆)

(hint: environ)

In [4]:
os.environ

environ({'GNOME_TERMINAL_SCREEN': '/org/gnome/Terminal/screen/b98a7475_508d_4380_be03_1eee1fff52e8', 'QT4_IM_MODULE': 'xim', 'GJS_DEBUG_OUTPUT': 'stderr', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'XDG_SESSION_TYPE': 'x11', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'kitos', 'USER': 'kitos', 'PATH': '/home/kitos/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'XDG_VTNR': '2', 'HOME': '/home/kitos', 'DISPLAY': ':0', 'SSH_AGENT_PID': '1608', 'LANG': 'ru_RU.UTF-8', 'TERM': 'xterm-color', 'SHELL': '/bin/bash', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'SESSION_MANAGER': 'local/kitos-HP-Laptop-15-bs0xx:@/tmp/.ICE-unix/1512,unix/kitos-HP-Laptop-15-bs0xx:/tmp/.ICE-unix/1512', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'CLUTTER_IM_MODULE': 'xim', 'TEXTDOMAIN': 'im-config', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'QT_ACCESS

20. Как игнорировать warrnings?

* Про datetime и timedelta 

https://www.guru99.com/date-time-and-datetime-classes-in-python.html

21. Вывести сегодняшнюю, вчерашнюю и завтрашнюю дату (☆☆☆)

In [32]:
from datetime import date
from datetime import time

print(datetime.today())
print(datetime.today() - timedelta(1))
print(datetime.today() + timedelta(1))

# today = date.today()
# year = today.year
# day = today.day
# month = today.month
# print(str(day) + ' ' + str(month) + ' ' + str(year))
# if (day == 1):
#     day1 = 31
#     month1 = month - 1
#     year1 = year
#     if (mounthe1 == 0):
#         year1 = year1 - 1
#         month1 = 12
#     print(str(day1) + ' ' + str(month1) + ' ' + str(year1))
# else:
#     print(str(day - 1) + ' ' + str(month) + ' ' + str(year))
    
# if (day == 31):
#     day1 = 1
#     month1 = month + 1
#     year1 = year
#     if (month1 == 13):
#         year1 = year1 + 1
#         month1 = 1
#     print(str(day1) + ' ' + str(month1) + ' ' + str(year1))
# else:
#     print(str(day + 1) + ' ' + str(month) + ' ' + str(year))

2020-02-04 13:35:36.280506
2020-02-03 13:35:36.280729
2020-02-05 13:35:36.280825


22. Вывести день недели сегодняшней даты (★☆☆)

In [18]:
today = date.today()
today.weekday()

1

23. Получить список дат за предыдущую неделю (★★☆)

In [38]:
from datetime import timedelta
print(datetime.today)
for i in range(1, 8):
    print(datetime.today() - timedelta(i))

<built-in method today of type object at 0xa33e60>
2020-02-03 13:38:58.431621
2020-02-02 13:38:58.431882
2020-02-01 13:38:58.432038
2020-01-31 13:38:58.432126
2020-01-30 13:38:58.432201
2020-01-29 13:38:58.432284
2020-01-28 13:38:58.432370


24. Вывести дату с часами и минутами, отформатировать в формате: 01.12.2019 00:12:54 (★★☆)
            
(hint: now().strftime())

In [25]:
from datetime import datetime
datetime.now().strftime("%Y.%m.%d %H:%M:%S")

'2020.02.04 13:30:13'

25. Исходя из текущей даты вычислить дату предыдущего понедельника (★★★)

In [30]:
from datetime import timedelta
print(datetime.now())
print(datetime.now() - timedelta(7))

2020-02-04 13:34:11.587356
2020-01-28 13:34:11.587451


# Numpy

### numpy в картинках (реально лучший):

https://jalammar.github.io/visual-numpy/

In [39]:
import numpy as np

1. Задать нулевой вектор размером 10 (★☆☆)

(hint: np.zeros)

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

2. Как найти размер занимаемой памяти любым массивом (★☆☆)

(hint: size, itemsize)

In [43]:
mas = [1,2,3,4]
np.size(mas)

AttributeError: module 'numpy' has no attribute 'itemsize'

3. Создать вектор из 10 нулей, кроме пятого элемента, который равен 1 (★☆☆)

In [46]:
mas = np.zeros(11)
mas[4] = 1
mas

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

4. Создать вектор от 10 до 50 включительно (★☆☆)

(hint:np.arange)

In [48]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

5. Перевернуть вектор (первый элемент будет последним) (★☆☆)

In [50]:
vec = np.arange(10, 51)
vec = vec[::-1]
vec

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

6. Создать матрицу 3х3 с элементами от 0 до 8 (★☆☆)

(hint: reshape)

In [59]:
np.arange(9).reshape(3, 3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Найти индексы не нулевых эемелентов в numpy array [1,2,0,0,4,0] (★☆☆)

(hint: np.nonzero)

In [62]:
np.array([1,2,0,0,4,0]).nonzero()

(array([0, 1, 4]),)

8. Создать матрицу 10x10 array с рандомными числами и найти минимум, максимум и среднее (★☆☆)

In [73]:
mas = np.random.random((10, 10))
print(mas)
print(mas.max())
print(mas.min())
print(mas.mean())

[[9.25494767e-01 8.64853014e-01 3.66738674e-01 6.47399681e-01
  9.76237898e-02 2.44229070e-01 2.08183451e-01 1.82740066e-01
  5.54938068e-01 7.48877811e-01]
 [1.83802894e-01 5.68169899e-01 8.71659645e-01 2.87255534e-01
  4.63888173e-01 6.77170114e-01 8.44595906e-01 4.82461085e-01
  7.75632425e-01 1.31493164e-01]
 [5.50099510e-01 5.53885901e-02 4.70736994e-01 1.96980624e-01
  1.98088208e-05 2.94725127e-01 5.70399926e-01 4.45662210e-01
  1.11087859e-01 1.14122285e-01]
 [4.14699840e-01 6.66382280e-01 7.02499262e-01 8.87931016e-01
  7.28263347e-01 3.73328454e-01 1.31008175e-01 1.12443143e-01
  3.29536800e-01 3.48953002e-01]
 [4.39896063e-01 3.04728010e-01 5.79869388e-02 9.58326626e-01
  6.12211220e-01 8.29073691e-01 9.74251456e-01 4.39023236e-01
  3.03658676e-02 4.35583354e-01]
 [1.87061547e-01 6.86644250e-01 4.92775040e-01 9.26255417e-01
  1.75930771e-01 3.50376616e-01 4.04588469e-01 5.40131193e-01
  7.85581999e-01 3.80741149e-01]
 [1.14651294e-01 7.59458896e-01 2.96920200e-01 1.67408391e

9. Создать матрицу 8x8 и заполнить 0 и 1 в стиле шахматной доски (★☆☆)

(hint: array[::n])

10. Нормализовать рандомную матрицу 5x5 (★☆☆)

(hint: (x - mean) / std)

11. Найти общие элементы между двумя массивами

(hint: np.intersect1d)

12. Извлечь целую часть рандомного массива чисел различными способами (максимум 5) (★★☆)

13. Создать рандомный вектор размера 10 и отсортировать его (★★☆)

14. Проверить одинаковы ли два рандомных массива А и B (★★☆)

(hint: np.allclose, np.array_equal)

15. Создать рандомный ветор размером 10 и максимальный элемент заменить на -1 (★★☆)

(hint: argmax)

16. Найдите самый близкий элемент к данному рандомному числу в векторе? (★★☆)

(hint: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index =  ???????
print(Z[index])

17. Посчитать среднее для каждой строки матрицы (★★☆)

18. Посчитать среднее со скользящим окном над массивом (★★★)

(hint: np.cumsum)

<img src="gifs/bender.gif" width="400">

# Regular expressions

* Cупер статья на все времена. Особенно понятно все про такие сложные штуки как lookaround. 

https://habr.com/ru/post/349860/


* Задания на регулярки

https://regexone.com/

* На этом сайте удобно тестировать регулярку, которую мучаешь, можно написать несколько примеров и тестировать на них. Важно не забывать выбирать Python:

https://regex101.com/

1. Из строки в файле data/rejson.txt вытащить хэш. Пример:

'master_guid': '<b>233880bb4c50d247f84edc9cac9e6e29</b>_2308194320'

# Pandas

* Pandas в картинках

https://jalammar.github.io/gentle-visual-intro-to-data-analysis-python-pandas/

* 10 minutes to pandas

https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html

* 🐼реально классный твиттер чувака с крутыми pandas tricks:
    
https://mobile.twitter.com/i/moments/1158828895547854849

<img src="gifs/inprogress.gif" width="400">